using System;
using System.Collections.Generic;
using System.Linq;
using System.Reflection;
using Core.Tests.TestSupport;
using Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Xunit;

namespace Core.Tests.Architecture;

// Migration-readiness guard. There is no EF migration history in this repo — the real
// database's schema was never generated by EF and can't be safely diffed against here — so
// these tests don't (and can't) prove the model matches production. What they do prove:
// every DbSet has an explicit IEntityTypeConfiguration (so a future entity can't silently
// fall back to bare conventions), and the model as configured is at least internally
// consistent enough to build. Before ever adding a real migration against the live database,
// baseline it first: snapshot the actual schema, reconcile any mismatch against these
// configurations, then create an initial migration and mark it as already-applied
// (INSERT into __EFMigrationsHistory) rather than running its generated SQL.
public class EfSchemaConfigurationTests
{
    [Fact]
    public void EveryNonIdentityDbSet_HasAMatchingEntityTypeConfiguration()
    {
        var dbSetEntityTypes = typeof(ApplicationDbContext)
            .GetProperties(BindingFlags.Public | BindingFlags.Instance)
            .Where(p => p.PropertyType.IsGenericType && p.PropertyType.GetGenericTypeDefinition() == typeof(DbSet<>))
            .Select(p => p.PropertyType.GetGenericArguments()[0])
            .Where(t => t.Namespace != null && t.Namespace.StartsWith("Domains.Entities"))
            .ToHashSet();

        var configuredEntityTypes = typeof(ApplicationDbContext).Assembly
            .GetTypes()
            .SelectMany(t => t.GetInterfaces()
                .Where(i => i.IsGenericType && i.GetGenericTypeDefinition() == typeof(IEntityTypeConfiguration<>))
                .Select(i => i.GetGenericArguments()[0]))
            .ToHashSet();

        var missing = dbSetEntityTypes.Except(configuredEntityTypes).ToList();

        Assert.True(missing.Count == 0,
            $"These DbSet entity types have no IEntityTypeConfiguration: {string.Join(", ", missing.Select(t => t.Name))}.");
    }

    [Fact]
    public void Model_BuildsAndCreatesSchemaWithoutError()
    {
        // EnsureCreated exercises every configuration together (keys, relations, indexes) —
        // a conflicting or malformed configuration fails here, not in production.
        using var factory = new SqliteContextFactory();
        using var context = factory.CreateContext();

        Assert.NotEmpty(context.Model.GetEntityTypes());
    }
}
