<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <AssemblyName>Domain</AssemblyName>
    <RootNamespace>Domain</RootNamespace>
  </PropertyGroup>

  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug|AnyCPU' ">
    <WarningLevel>4</WarningLevel>
  </PropertyGroup>
  <ItemGroup>
    <Compile Remove="Catalog\**" />
    <EmbeddedResource Remove="Catalog\**" />
    <None Remove="Catalog\**" />
  </ItemGroup>

</Project>
